d1 <- d1 %>% 
  filter(QID1 == 1 & DistributionChannel == "anonymous") %>% 
  select(region:job, job_other = job_11_TEXT,
         income:subj_socialclass, polvuln_1 = Q9_1, 
         polvuln_2 = Q9_2, polvuln_3 = Q9_3, polvuln_4 = Q9_4, 
         polvuln_5 = Q9_5, cultvuln_1 = Q10_1, cultvuln_2 = Q10_2, 
         cultvuln_3 = Q10_3, cultvuln_4 = Q10_4,
         relative_deprivation_1:collective_narcism_9, 
         colnostalgia_1 = `collective-nostalgia_1`,
         colnostalgia_2 = `collective-nostalgia_2`,
         colnostalgia_3 = `collective-nostalgia_3`,
         colnostalgia_4 = `collective-nostalgia_4`,
         populist_attitudes_1:populist_attitudes_14,
         gender:ideology, nostalgia:nostalgic_message,
         mc1 = manipulation_check_1,
         mc2 = manipulation_check_2,
         mc3 = manipulation_check_3) %>% 
  mutate(region = recode(region, 
                         `1` = "Big Cities",
                         `5` = "East Netherlands",
                         `9` = "West Netherlands",
                         `10` = "South Netherlands",
                         .default = "NA"),
         education = recode(education,
                            `1` = "High Levels of Education",
                            `2` = "High Levels of Education",
                            `3` = "Medium Levels of Education",
                            `4` = "Medium Levels of Education",
                            `5` = "Low Levels of Education",
                            `6` = "Low Levels of Education",
                            `7` = "Low Levels of Education",
                            .default = "NA"),
         employment = recode(employment,
                             `2` = 0,
                             `1` = 1),
         job = recode(job,
                      `1` = "Agrariër, bosbouwer of visser (incl. hovenier)",
                      `2` = "Militair beroep",
                      `3` = "Hogere manager (incl. beleidsvoerende functie)",
                      `4` = "Docent, onderzoeker, ingenieur",
                      `5` = "Hoger opgeleide specialist",
                      `6` = "Gespecialiseerd beroep",
                      `7` = "Administratief beroep",
                      `8` = "Ambachtswerker",
                      `9` = "Dienstverlenend beroep of verkoper",
                      `10` = "Chauffeur, machinebediener of assemblagemedewerker",
                      `11`= "Ander", 
                      .default = "NA"),
         income = recode(income,
                         `1` = "No income",
                         `4` = "500 or less",
                         `5` = "501-1000",
                         `6` = "1001-1500",
                         `7` = "1501-2000",
                         `8` = "2001-2500",
                         `9` = "2501-3000",
                         `10` = "3001-3500",
                         `11` = "3501-4000",
                         `12` = "4001-4500",
                         `13` = "4501-5000",
                         `14` = "5000 or more", 
                         .default = 'NA'),
         subj_socialclass = na_if(subj_socialclass, 6),
         gender = recode(gender,
                         `1` = "Male",
                         `2` = "Female", .missing = "NA",
                         .default = "NA"),
         ideology = ideology - 1,
         ideology = na_if(ideology, 11),
         check_nostalgia = ifelse(nostalgic_message == "yes" & mc1 == 4, 1,
                           ifelse(nostalgic_message == "yes" & mc1 == 5, 1, 0)),
         check_immigration = ifelse(issue == "immigration" & mc2 == 4, 1,
                             ifelse(issue == "immigration" & mc2 == 5, 1, 0)),
         check_corruption = ifelse(issue == "corruption" & mc3 == 4, 1,
                            ifelse(issue == "corruption" & mc3 == 5, 1, 0)),
         message = "anonymous")


d2 <- d2 %>% 
  mutate(date = as.character(map(strsplit(as.character(StartDate), split = " "), 1)),
         nostalgic_message = ifelse(date>"2022-06-08", "no", nostalgic_message)) %>% 
  filter(QID1 == 1 & DistributionChannel == "anonymous") %>% 
  select(gender = Gender, age = Age, education = Education,
         job = Work, vote = `Political Q's`, vote_other = `Political Q's _18_TEXT`,
         ideology, nationalism_1 = `Gedragen als NL`, nationalism_2 = `Nederland beter`,
         nationalism_3 = `Land steunen`, nationalism_4 = `Staatsburger NL`, 
         nationalism_5 = `Internationale sport`, nationalism_6 = `NL schaam`, 
         nationalism_7 = `Trots NL`, agreeable_1 = `Agreeable - zorg`,
         agreeable_2 = `Agreeable - interess`, agreeable_3 = QID20,
         agreeable_4 = Q21, agreeable_5 = Q22, agreeable_6 = Q23,
         agreeable_7 = Q24, agreeable_8 = Q25, agreeable_9 = Q26,
         agreeable_10 = Q27, life_satisf = `Life satisfaction`,
         trust_1 = `Vertrouwen institut_1`, trust_2 = `Vertrouwen institut_2`,
         trust_3 = `Vertrouwen institut_3`, trust_4 = `Vertrouwen institut_4`,
         trust_5 = `Vertrouwen institut_5`, trust_6 = `Vertrouwen institut_6`,
         trust_7 = `Vertrouwen institut_7`, trust_8 = `Vertrouwen institut_8`,
         trust_9 = `Vertrouwen institut_9`, trust_10 = `Vertrouwen institut_10`,
         trust_11 = `Vertrouwen institut_11`, 
         colnostalgia_1 = `collective-nostalgia_1`,
         colnostalgia_2 = `collective-nostalgia_2`,
         colnostalgia_3 = `collective-nostalgia_3`,
         colnostalgia_4 = `collective-nostalgia_4`,
         populist_attitudes_1:populist_attitudes_14,
         mc1 = `Manipulation check_1`, mc2 = `Manipulation check_2`,
         mc3 = `Manipulation check_3`, nostalgic_message, issue, nostalgia) %>% 
  mutate(gender = recode(gender,
                         `1` = "Male",
                         `2` = "Female", 
                         .default = "NA"),
         education = recode(education,
                            `1` = "High Levels of Education",
                            `2` = "High Levels of Education",
                            `3` = "Medium Levels of Education",
                            `4` = "Medium Levels of Education",
                            `5` = "Low Levels of Education",
                            `6` = "Low Levels of Education",
                            `7` = "Low Levels of Education",
                            .default = "NA"),
         job = recode(job,
                      `1` = "Agrariër, bosbouwer of visser (incl. hovenier)",
                      `2` = "Militair beroep",
                      `3` = "Hogere manager (incl. beleidsvoerende functie)",
                      `4` = "Docent, onderzoeker, ingenieur",
                      `5` = "Hoger opgeleide specialist",
                      `6` = "Gespecialiseerd beroep",
                      `7` = "Administratief beroep",
                      `8` = "Ambachtswerker",
                      `9` = "Dienstverlenend beroep of verkoper",
                      `10` = "Chauffeur, machinebediener of assemblagemedewerker",
                      `11`= "Ander", .default = "NA"),
         ideology = ideology - 1,
         ideology = na_if(ideology, 11),
         vote = recode(vote,
                       `1` = "Bij1",
                       `2` = "CDA",
                       `3` = "ChristenUnie",
                       `5` = "D66",
                       `7` = "Fvd",
                       `8` = "GroenLinks",
                       `9` = "JA21",
                       `11` = "PvdD",
                       `12` = "PVV",
                       `14` = "SP",
                       `15` = "VOLT",
                       `16` = "VVD",
                       `17` = "50+",
                       `18` = "Other party",
                       .default = "NA"),
         check_nostalgia = ifelse(nostalgic_message == "yes" & mc1 == 4, 1,
                           ifelse(nostalgic_message == "yes" & mc1 == 5, 1, 0)),
         check_immigration = ifelse(issue == "immigration" & mc2 == 4, 1,
                             ifelse(issue == "immigration" & mc2 == 5, 1, 0)),
         check_corruption = ifelse(issue == "corruption" & mc3 == 4, 1,
                            ifelse(issue == "corruption" & mc3 == 5, 1, 0)),
         message = "party")

